\input texinfo @c -*-texinfo-*-
@c %**start of header (This is for running texinfo on a region.)
@setfilename epeg.info
@settitle epeg jpeg thumbnailer
@c %**end of header (This is for running texinfo on a region.)

@include version.texi

@ignore
@ifinfo
@format
START-INFO-DIR-ENTRY
* epeg: (epeg.info). The epeg jpeg thumbnailer.
END-INFO-DIR-ENTRY
@end format
@end ifinfo
@end ignore

@titlepage
@title The epeg jpeg thumbnailer
@subtitle A Guide for using the epeg jpeg thumbnailer library
@subtitle Edition @value{VERSION}
@subtitle @value{UPDATED}
@author Carsten Haitzler and Eric Gallager
@c Include the Distribution inside the titlepage
@c environment so that headings are turned off.
@c Headings on and off do not work.
@page
@vskip 0pt plus 1filll
Copyright @copyright{} @value{UPDATED-MONTH} Carsten Haitzler and various contributors
@sp 2
This is Edition @value{VERSION} of @cite{The epeg jpeg thumbnailer library}, @* for the
@value{VERSION} version of the Enlightenment implementation of epeg.
@sp 2
Published by no one.
@end titlepage

@c only plain tex can be embedded, NOT LaTeX...
@c have to remove large chunks of LaTeX-isms...
@iftex
@tex
 0.0.1
[Author:]Carsten Haitzler
[Date:]2000-2003

 What is Epeg?
  An IMMENSELY FAST JPEG thumbnailer library API.

 Why write this?
  It is a convenience library API to using libjpeg to load JPEG images destined to be turned into thumbnails of the original,
  saving information with these thumbnails,
  retreiving it and managing to load the image ready for scaling with the minimum of fuss and CPU overhead.

  This means that it is insanely fast at loading large JPEG images and scaling them down to tiny thumbnails.
  Its speedup will be proportional to the size difference between the source image and the output thumbnail size as a count of their pixels.

  It makes use of libjpeg features of being able to load an image by only decoding the DCT coefficients needed to reconstruct an image of the size desired.
  This gives a massive speedup.
  If you do not try and access the pixels in a format other than YUV (or GRAY8 if the source is grascale),
  then it also avoids colorspace conversions as well.

  Using the library is very easy.

  It is a very simple library that just makes life easier when tyring to generate lots of thumbnails for large JPEG images as quickly as possible.
  Your milage may vary, but it should save you lots of time and effort in using libjpeg in general.
@end tex
@c having a tex section like that is pretty pointless with the LaTeX-isms removed...
@end iftex

@ifinfo
@node Top, (dir), (dir)
@top General Introduction
@c Preface or Licensing nodes should come right
@c after the Top node, in `unnumbered' sections,
@c then the chapter, `What is epeg'.
This file documents @code{epeg}, an IMMENSELY FAST JPEG thumbnailer library API.
This is Edition @value{VERSION} of @cite{The epeg jpeg thumbnailer library},
for the @value{VERSION} version of the Enlightenment implementation of epeg.@refill
@end ifinfo

@summarycontents
@contents
@bye

